server:
  port: 8080
spring:
  application:
    name: spring-security-basic
  datasource:
    username: postgres
    password: 280202
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security-database
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # or update
    generate-ddl: true

